import Head from "next/head";
import Image from "next/image";
import HeroComp from "../public/HeroComp";
import Service from "../public/Service";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-[90%] mx-auto">
        <section className="">
          <HeroComp />
        </section>
        <section className="w-full min-h-screen ">
          <Service />
        </section>
      </main>
      {/* <footer className=""></footer> */}
    </div>
  );
}
